repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280
    hooks:
    - id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    - id: mypy
-   repo: https://github.com/pre-commit/mirrors-pytest
    rev: ''
    hooks: []
-   repo: https://github.com/pre-commit/mirrors-black
    rev: 22.3.0
    hooks:
    - id: black

# Local hook to run pytest
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest -q
      language: system
      pass_filenames: false
      always_run: true
